### ISSUE TITLE
require in Usage in ReadMe is wrong

### ISSUE THREAD

**Issue by utmath8** [majorek31/minecraft-rcon-client#8]
At the begining of Usage in ReadMe,
it is coded as 
`const Rcon = require('minecraft-rcon-protocol')`
but this is wrong.
We should rewrite it as follows:
`const {Rcon} = require('minecraft-rcon-client')`

**Comment by majorek31** [comment]
Yes, you are right, I will change it in next update. Thank you for reporting this to me.
